version: '3'

services:
  esrgan:
    build: .
    image: esrgan-gpu-tf2.11:latest
    container_name: esrgan-tf211-container
    volumes:
      - ./ESRGAN:/workspace
      - /media/adalab/Bodega/JuanCruz/Microscopy:/media/adalab/Bodega/JuanCruz/Microscopy
      - ./ESRGAN/logs:/workspace/logs
      - ./ESRGAN/model:/workspace/model
      - ./cache:/workspace/cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONPATH=/workspace
      - CUDA_VISIBLE_DEVICES=0
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '16gb'  # Aumentado para manejar grandes batches
    tty: true
    stdin_open: true
    command: bash
