# Config File for Distillation
mse_checkpoint: "checkpoints/mse_checkpoints/"
adversarial_checkpoint: "checkpoints/adversarial_checkpoints/"
train:
  iterations: 1
  print_step: 100
  checkpoint_step: 1000
  balance_factor: 0.2 # alpha of Adversarial Training
student_network: "name1"
student_networks_config:
  name1:
    param1: 1
    param2: "two"
    paramN: "N"
  name2:
    param1: 1
    param2: "two"
    paramN: "N"
  name3:
    param1: 1
    param2: "two"
    paramN: "N"
