# Config File for Distillation
teacher_directory: "../E2_ESRGAN"
teacher_config: "../E2_ESRGAN/config/config.yaml"
checkpoint_path:
  comparative_checkpoint: "checkpoints/mse_checkpoints/"
  adversarial_checkpoint: "checkpoints/adversarial_checkpoints/"

hr_size: [256, 256, 3]
train:
  iterations: 1
  print_step: 100
  num_steps: 10000
  checkpoint_step: 100
  decay_rate: 0.5
  decay_steps:
    - 6100
    - 9000
    - 13500
  balance_factor: 0.2 # alpha of Adversarial Training

scale_factor: 2
scale_value: 2
student_network: "rrdb_student"
student_config:
  vgg_student:
    trunk_depth: 3 # Minimum 2
    # growth_channels: 32
    use_bias: True
  residual_student:
    trunk_depth: 2
    use_bias: True
    residual_scale_beta: 0.8
  rrdb_student:
    rdb_config:
      depth: 3
      residual_scale_beta: 0.2
    rrdb_config:
      rdb_units: 2
      residual_scale_beta: 0.2
    trunk_size: 3
    growth_channels: 32
