RDB:
  residual_scale_beta: 0.2
batch_size: 2
checkpoint_path:
  phase_1: checkpoints/phase_1
  phase_2: checkpoints/phase_2
dataset:
  hr_dimension: 1024
  lr_dimension: 512
  name: Microscopy
  scale_method: bicubic
discriminator:
  kimianet_weights: /workspace/model-kimianet/KimiaNetKerasWeights.h5
  num_features: 32
  type: optimized_vgg
interpolation_parameter: 0.8
print_step: 100
train_combined:
  adam:
    beta_1: 0.9
    beta_2: 0.999
    decay:
      factor: 0.5
      step:
      - 2000
      - 6000
      - 10000
      - 15000
      - 25000
    discriminator_lr: 5.0e-06
    initial_lr: 2.0e-05
  eta: 0.01
  lambda: 0.005
  num_steps: 50000
  perceptual_loss_type: L1
train_psnr:
  adam:
    beta_1: 0.9
    beta_2: 0.999
    decay:
      factor: 0.5
      step: 30000
    initial_lr: 0.0003
  num_steps: 60000
