RDB:
  residual_scale_beta: 0.2
batch_size: 4
checkpoint_path:
  phase_1: checkpoints/phase_1
  phase_2: checkpoints/phase_2
dataset:
  hr_dimension: 512
  name: Microscopy
  scale_method: bicubic
interpolation_parameter: 0.8
print_step: 1000
train_combined:
  adam:
    beta_1: 0.9
    beta_2: 0.999
    decay:
      factor: 0.5
      step:
      - 9000
      - 30000
      - 50000
      - 100000
      - 200000
      - 300000
    initial_lr: 5.0e-05
  eta: 0.01
  lambda: 0.005
  num_steps: 400000
  perceptual_loss_type: L1
train_psnr:
  adam:
    beta_1: 0.9
    beta_2: 0.999
    decay:
      factor: 0.5
      step: 200000
    initial_lr: 0.0002
  num_steps: 600000
